FROM python:3.13-slim-bullseye
RUN mkdir /app \
	&& mkdir /log
# RUN apt-get update && apt-get install -y curl vim
# RUN apt-get clean
RUN pip install --upgrade pip

WORKDIR /app

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml /app
RUN poetry config virtualenvs.create false
RUN poetry install --without dev -n --no-ansi
RUN yes | poetry cache clear . --all

COPY . /app
EXPOSE 8000

ENTRYPOINT [ "./run.sh" ]
