services:
  app:
    container_name: reporter
    build:
      context: .
    volumes:
      - "./logs/app:/root/logs"
    ports:
      - "8080:8080"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
